name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-haskell@v2
      with:
        ghc-version: '9.2.7' 
        cabal-version: '3.10'

    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal
          dist-newstyle
        key: ${{ runner.os }}-ghc-9.2.7-${{ hashFiles('**/*.cabal', '**/cabal.project*') }}

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks claude-haskell

    - name: Build & Test
      run: |
        cabal build --enable-tests --enable-benchmarks
        cabal test all --test-show-details=streaming
